name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "The branch name to base the release/staging on"
        required: true
        default: "main"

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Force push to release/staging branch
        run: |
          # Get the branch to base staging on from the workflow input
          BASE_BRANCH=${{ github.event.inputs.base_branch }}

          # Checkout the base branch and update it
          git checkout $BASE_BRANCH
          git pull origin $BASE_BRANCH

          # Force push the base branch to release/staging
          git push -f origin $BASE_BRANCH:release/staging
